//
//  main.cpp
//  leetcode
//
//  Created by hatlonely on 16/1/10.
//  Copyright © 2016年 hatlonely. All rights reserved.
//

#define MAIN_NAMESPACE(name) namespace name { extern int main(int argc, const char *argv[]); }

MAIN_NAMESPACE(two_sum)
MAIN_NAMESPACE(add_two_numbers)
MAIN_NAMESPACE(longest_substring_without_repeating_characters)
MAIN_NAMESPACE(median_of_two_sorted_arrays)
MAIN_NAMESPACE(longest_palindromic_substring)
MAIN_NAMESPACE(zigzag_conversion)
MAIN_NAMESPACE(reverse_integer)
MAIN_NAMESPACE(string_to_integer)
MAIN_NAMESPACE(palindrome_number)
MAIN_NAMESPACE(regular_expression_matching)
MAIN_NAMESPACE(container_with_most_water)
MAIN_NAMESPACE(integer_to_roman)
MAIN_NAMESPACE(roman_to_integer)
MAIN_NAMESPACE(longest_common_prefix)
MAIN_NAMESPACE(three_sum)
MAIN_NAMESPACE(three_sum_closest)
MAIN_NAMESPACE(letter_combinations_of_a_phone_number)
MAIN_NAMESPACE(four_sum)
MAIN_NAMESPACE(remove_nth_node_from_end_of_list)
MAIN_NAMESPACE(valid_parentheses)
MAIN_NAMESPACE(merge_two_sorted_lists_my_submissions_question)
MAIN_NAMESPACE(generate_parentheses)
MAIN_NAMESPACE(merge_k_sorted_lists)
MAIN_NAMESPACE(swap_nodes_in_pairs)
MAIN_NAMESPACE(reverse_nodes_in_k_group)
MAIN_NAMESPACE(remove_duplicates_from_sorted_array)
MAIN_NAMESPACE(remove_element)
MAIN_NAMESPACE(implement_strstr)
MAIN_NAMESPACE(divide_two_integers)
MAIN_NAMESPACE(substring_with_concatenation_of_all_words)
MAIN_NAMESPACE(next_permutation)
MAIN_NAMESPACE(longest_valid_parentheses)
MAIN_NAMESPACE(search_in_rotated_sorted_array)
MAIN_NAMESPACE(search_for_a_range)
MAIN_NAMESPACE(search_insert_position)
MAIN_NAMESPACE(valid_sudoku)
MAIN_NAMESPACE(sudoku_solver)
MAIN_NAMESPACE(count_and_say)
MAIN_NAMESPACE(combination_sum)
MAIN_NAMESPACE(combination_sum_ii)
MAIN_NAMESPACE(first_missing_positive)
MAIN_NAMESPACE(trapping_rain_water)
MAIN_NAMESPACE(multiply_strings)
MAIN_NAMESPACE(wildcard_matching)
MAIN_NAMESPACE(jump_game_ii)
MAIN_NAMESPACE(permutations)
MAIN_NAMESPACE(permutations_ii)
MAIN_NAMESPACE(rotate_image)
MAIN_NAMESPACE(group_anagrams)
MAIN_NAMESPACE(pow_x_n)
MAIN_NAMESPACE(n_queens)
MAIN_NAMESPACE(n_queens_ii)
MAIN_NAMESPACE(maximum_subarray)
MAIN_NAMESPACE(spiral_matrix)
MAIN_NAMESPACE(jump_game)
MAIN_NAMESPACE(merge_intervals)
MAIN_NAMESPACE(insert_interval)
MAIN_NAMESPACE(length_of_last_word)
MAIN_NAMESPACE(spiral_matrix_ii)
MAIN_NAMESPACE(permutation_sequence)
MAIN_NAMESPACE(rotate_list)
MAIN_NAMESPACE(unique_paths)
MAIN_NAMESPACE(unique_paths_ii)
MAIN_NAMESPACE(minimum_path_sum)
MAIN_NAMESPACE(valid_number)
MAIN_NAMESPACE(plus_one)
MAIN_NAMESPACE(add_binary)
MAIN_NAMESPACE(text_justification)
MAIN_NAMESPACE(sqrt_x)
MAIN_NAMESPACE(climbing_stairs)
MAIN_NAMESPACE(simplify_path)
MAIN_NAMESPACE(edit_distance)
MAIN_NAMESPACE(set_matrix_zeroes)
MAIN_NAMESPACE(search_a_2d_matrix)
MAIN_NAMESPACE(sort_colors)
MAIN_NAMESPACE(minimum_window_substring)
MAIN_NAMESPACE(combinations)
MAIN_NAMESPACE(subsets)
MAIN_NAMESPACE(word_search)
MAIN_NAMESPACE(remove_duplicates_from_sorted_array_ii)
MAIN_NAMESPACE(search_in_rotated_sorted_array_ii)
MAIN_NAMESPACE(remove_duplicates_from_sorted_list_ii)
MAIN_NAMESPACE(remove_duplicates_from_sorted_list)
MAIN_NAMESPACE(largest_rectangle_in_histogram)
MAIN_NAMESPACE(maximal_rectangle)
MAIN_NAMESPACE(partition_list)
MAIN_NAMESPACE(scramble_string)
MAIN_NAMESPACE(merge_sorted_array)
MAIN_NAMESPACE(gray_code)
MAIN_NAMESPACE(subsets_ii)
MAIN_NAMESPACE(decode_ways)
MAIN_NAMESPACE(reverse_linked_list_ii)

int main(int argc, const char *argv[]) {
    return reverse_linked_list_ii::main(argc, argv);
}


